{
 "title": "Firewall Logs",
 "tags": [
  "Elasticsearch",
  "Firewall",
  "Log Analyzer",
  "PFsense"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "iface",
    "label": "Interface",
    "query": "{\"find\": \"terms\", \"field\":\"iface\",\"size\": \"1000000\" }"
   },
   {
    "name": "src_ip",
    "label": "Source IP",
    "query": "{\"find\": \"terms\", \"field\":\"src_ip\",\"query\":\"iface iface:$iface\",\"size\": \"1000000\" }"
   },
   {
    "name": "dport",
    "query": "{\"find\": \"terms\", \"field\":\"dest_port\",\"query\":\"iface iface:$iface\",\"size\": \"1000000\" }"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "GeoIP Block source ip location by $iface",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "src_ip",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "src_location", "id": "2", "settings": { "precision": 7 }, "type": "geohash_grid" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "iface:$iface AND src_ip:$src_ip",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top ip Block by $iface",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "src_ip",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "src_ip_city_name",
       "id": "8",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "src_ip_country_code",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "iface:$iface AND src_ip:$src_ip",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Real time logs by iface:$iface",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 10000 },
       "type": "raw_document"
      }
     ],
     "query": "iface:$iface  AND dest_port:$dport",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Firewall Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "iface:$iface AND dest_port:$dport AND src_ip:$src_ip",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Match by interface $iface",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "iface",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "iface:$iface AND dest_port:$dport AND src_ip:$src_ip",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Events by $iface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "iface:$iface AND dest_port:$dport AND src_ip:$src_ip",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Rules triggered on $iface by Country",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "Triggers" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "src_ip_country_code",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "iface:$iface AND dest_port:$dport AND src_ip:$src_ip -src_ip:62.155.248.*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Protocols by interface $iface",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "proto",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "iface:$iface AND dest_port:$dport AND src_ip:$src_ip",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Destination Port by iface:$iface",
   "type": "savantly-heatmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "format": "none",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "PortServiceName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "iface:$iface  AND dest_port:$dport AND src_ip:$src_ip",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Rules triggered on $iface by City",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "Cantidad de Accesos" }
   ],
   "targets": [
    {
     "alias": "City: {{term src_ip_city_name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "src_ip_city_name",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "iface:$iface  AND dest_port:$dport AND src_ip:$src_ip",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 10 port Destination Block by $iface",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "Port: {{PortServiceName}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "PortServiceName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "iface:$iface  AND dest_port:$dport AND src_ip:$src_ip",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}