apiVersion: 1

deleteDatasources:
  - name: ntop
    orgId: 1
  - name: pfsensefw
    orgId: 1

datasources:
- name: ntop
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  password: ntop
  user: ntop
  database: ndpi
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: ""
    tlsClientCert: ""
    tlsClientKey: ""
  version: 1
  editable: true

- name: pfsensefw
  type: elasticsearch
  access: proxy
  database: "pfsense_*"
  url: http://elasticsearch:9200
  jsonData:
    esVersion: "7.10"
    timeField: "timestamp"
